module.exports.LANGUAGES = {
  "En" : {
    ".link1" : "Blockchain 101",
    ".link2" : "Hackathon",
    ".link3" : "Toolsets",
    ".link4" : "Examples",
    ".link5" : "remix IDE",
    "#main_title" : "Quorum Korea Toolkits & Examples",
    "#main_subtitle1" : "This site is the hub for Quorum Korea's Toolkits and repositories. Here, you can find easy access to a variety of translated docs, helpful code bits, and examples to help you develop on Quorum.",
    "#main_subtitle2" : "If you know blockchain and Ethereum already click the button below. If you are a beginner, check out the 'Start Here' section above.",
    "#main_button1" : "Jump In!",
    "#main_button2" : "Orientation Decks",
    "#sec_header1" : "Toolsets",
    "#sec_sub1" : "Some helpful tools for building Quorum apps.",
    "#tool_descrip1" : "This Repo is the main repo for Quorum's Eth-based Blockchain solution",
    "#tool_descrip2" : "Enterprise Implementation of Quorum's transaction manager",
    "#tool_descrip3" : "An integrated development environment and SDK for Ethereum-like ledgers",
    "#tool_descrip4" : "A Peer-to-peer encrypted message exchange",
    "#tool_descrip5" : "This project contains tools for running Quorum clusters and integration testing Quorum.",
    "#tool_descrip6" : "Deploy Quorum network in a cloud provider of choice",
    "#sec2_header" : "Examples",
    "#sec2_sub" : "Examples of Quorum Usage and Chain Deployment",
    "#sec2_header1" : "TESTING",
    "#sec2_body1" : "Starts up a fully-functioning Quorum environment consisting of 7 independent nodes. From this example one can test consensus, privacy, and all the expected functionality of an Ethereum platform.",
    "#sec2_header2" : "SIMULATION",
    "#sec2_body2" : "Starts up a set of 5 nodes that simulates a Real-time Gross Setlement environment with 3 banks, one regulator (typically a central bank) and an observer that cannot access the private data.",
    "#sec2_header3" : "DAPP EXAMPLE",
    "#sec2_body3" : "Basic Dapp demonstrating Hashing of a File and Saving it to a basic Quorum Blockchain. Requires access to a Quorum RPC to run.",
    ".drop_sec1" : "1.) Understanding Quorum",
    ".drop_sub1" : "Quorum 101",
    ".drop_sec2" : "2.) Getting Setup",
    ".drop_sub2" : "Get a Quorum Chain Going",
    ".drop_sec3" : "3.) Using Quorum",
    ".drop_sub3" : "Start Developing",
    ".drop_sec4" : "FAQ",
    ".drop_sub4" : "Frequently Asked Questions",
    ".drop_sec5" : "Ethereum",
    ".drop_sub5" : "Understanding Ethereum",
    ".drop_sec6" : "API",
    ".drop_sub6" : "Web3 & Quorum (EN)",
    ".drop_sec7" : "View Full Wiki",
    ".drop_sub7" : "Checkout Korean Wiki on Github",
    ".drop_sec8" : "Enterprise Blockchain",
    ".drop_sub8" : "Download Enterprise Blockchain Deck",
    ".drop_cc_title" : "Main Repository",
    ".drop_cc_body" : "This is the official Quorum Repository (English)",
  },
  "Ko" : {
    ".link1" : "블록체인 101",
    ".link2" : "해커톤",
    ".link3" : "툴킷",
    ".link4" : "Examples",
    ".link5" : "Remix IDE",
    "#main_title" : "쿼럼 코리아 툴킷 및 예시",
    "#main_subtitle1" : "본 사이트는 쿼럼 코리아의 툴킷과 데이터베이스를 제공합니다. 여기서는 다양한 번역 문서, 유용한 코드 및 쿼럼을 이용해 개발할 수 있도록 도와주는 다양한 예들을 쉽게 찾아볼 수 있습니다.",
    "#main_subtitle2" : "블록체인 및 이더리움에 대해 이미 알고 있는 경우 아래 버튼을 클릭하십시오. 초보자라면 위의 'Start Here' 섹션을 확인하십시오.",
    "#main_button1" : "Jump In!",
    "#main_button2" : "오리엔테이션 자료",
    "#sec_header1" : "툴킷",
    "#sec_sub1" : "쿼럼 애플리케이션 구축에 유용한 툴.",
    "#tool_descrip1" : "이 저장소는 쿼럼의 이더리움 기반 블록체인 솔루션의 주요 내용을 담고 있습니다",
    "#tool_descrip2" : "쿼럼의 트랜잭션 매니저 엔터프라이즈 구현",
    "#tool_descrip3" : "이더리움과 유사한 원장의 통합 개발 환경과 SDK",
    "#tool_descrip4" : "P2P 암호화 메시지 교환",
    "#tool_descrip5" : "이 프로젝트에는 쿼럼 클러스터 실행 및 쿼럼 통합 테스트를 위한 도구가 포함되어 있습니다.",
    "#tool_descrip6" : "원하는 클라우드 공급업체 상에 쿼럼 네트워크 구축",
    "#sec2_header" : "Examples",
    "#sec2_sub" : "쿼럼 사용 및 체인 구축 예제",
    "#sec2_header1" : "테스트",
    "#sec2_body1" : "7개의 독립 노드로 구성되어 완전하게 작동하는 쿼럼 환경을 시작합니다. 이 예에서는 합의, 프라이버시 및 이더리움 플랫폼에서 예상 가능한 모든 기능을 테스트할 수 있습니다.",
    "#sec2_header2" : "시뮬레이션",
    "#sec2_body2" : "3개의 은행, 1개의 규제기관(일반적으로 중앙은행) 및 개인 데이터에 액세스할 수 없는 관찰자로 실시간 총 설정 환경을 시뮬레이션하는 5개의 노드 집합을 실행합니다.",
    "#sec2_header3" : "DAPP 예제",
    "#sec2_body3" : "파일 해싱을 시연하고 기본 쿼럼 블록체인(Quorum Blockchain)에 저장하는 기본 Dapp. 쿼럼 RPC를 실행하려면 액세스 권한이 필요함.",
    ".drop_sec1" : "1.) Understanding Quorum",
    ".drop_sub1" : "쿼럼 101",
    ".drop_sec2" : "2.) Getting Setup",
    ".drop_sub2" : "쿼럼 체인 만들기",
    ".drop_sec3" : "3.) Using Quorum",
    ".drop_sub3" : "개발 시작",
    ".drop_sec4" : "FAQ",
    ".drop_sub4" : "자주 묻는 질문",
    ".drop_sec5" : "Ethereum",
    ".drop_sub5" : "Etherum 이해",
    ".drop_sec6" : "API",
    ".drop_sub6" : "Web3 & Quorum (EN)",
    ".drop_sec7" : "전체 위키 보기",
    ".drop_sub7" : "Github에서 한국어 위키 체크아웃",
    ".drop_sec8" : "Enterprise Blockchain",
    ".drop_sub8" : "엔터프라이즈 블록체인 데크 다운로드",
    ".drop_cc_title" : "Main Repository",
    ".drop_cc_body" : "공식 쿼럼 데이터저장소입니다. (English)"
  }
}
